### ISSUE TITLE
Feature request: shareable look and feel of annotations

### ISSUE THREAD

**Issue by dpalic** [eclipse-pmd/eclipse-pmd#11]
for being able to share a default setup for a full team it shall be possible to have the look and feel configured on project level.
This would ensure, that the juniors entering the team see exactly what a senior is also seeing. Later are usually not very often changing their settings, what juniors by nature typically do to try out things.

so this section shall be possible to configure on project level

![image](https://user-images.githubusercontent.com/1399203/85344512-2db1d000-b4f0-11ea-80c4-885ecd34496a.png)

means the 

- priorities
- shapes
- icons

shall be possible to commit on project level

other aspect, even if controversary:
Also it is more convinient to be able as a senior or tech lead to decide on which level the configuration shall reside. If the tech lead decides it has to be mandatory for the team (by commiting on project level) there are communication paths to the tech lead to modify shapes and colors to match all team mates. (indpendently of dark or light theme, of having blind or disabled persons in the team. In the other case the control is getting lost by a tech lead how the configuration evolves in a team.

**Comment by eclipse-pmd** [comment]
It looks like you are using [pmd-eclipse-plugin](https://github.com/pmd/pmd-eclipse-plugin), the other PMD plugin for eclipse. So you have to post your feature request in their repository.
