### ISSUE TITLE
License Text is broken

### ISSUE THREAD

**Issue by BeckerWdf** [eclipse-pmd/eclipse-pmd#20]
When installing the PMD plugin I see that your license text is broken for some of your plugins. See the "&quot;" stuff in the text:

![image](https://user-images.githubusercontent.com/28338612/109480415-ca633f00-7a7b-11eb-83cd-3d20f4da3bef.png)

The license text for "eclipse-pmd Core" in contrast is fine.

**Comment by eclipse-pmd** [comment]
You are running version 1.25 of eclipse-pmd. This issue has been fixed in version 2.1 over a year ago. Please update to the current version 2.12.
