### ISSUE TITLE
Show PMD Rule in Tooltip

### ISSUE THREAD

**Issue by numeralnathan** [eclipse-pmd/eclipse-pmd#26]
When the user puts their mouse over the PMD violation, a tooltip pops up and shows the message of the rule.  Please add the PMD rule name to the tooltip.  This will make it easy for the user to copy the rule name and paste it into a @SuppressWarnings.  Without this, the user has to go to the PMD documentation and find the text of the rule to get the rule name.

**Comment by acanda** [comment]
There is already a quick fix that creates a `@SuppressWarnings` annotation with the respective rule name.
![grafik](https://user-images.githubusercontent.com/174978/131266255-615dd1e6-e267-4c52-98f4-abb71bbea70c.png)

**Comment by nathanspectacular** [comment]
I do not see the quick fix in my tool tip.

![image](https://user-images.githubusercontent.com/88563519/131574058-90e8b008-9427-4554-ac66-25b68512fda7.png)

Is there something I need to configure to get the quick fix to show up?  Quick fixes show up for other types of Eclipse warnings.

**Comment by acanda** [comment]
Clicking on the warning icon will open the context menu with the quick fix.
