### ISSUE TITLE
No repository found at http://www.acanda.ch/eclipse-pmd/release/latest

### ISSUE THREAD

**Issue by nkavian** [eclipse-pmd/eclipse-pmd#27]
I'm using Java 11 and the latest version of Eclipse 2021..

Trying to add it from the marketplace or using the drag and drop method just generates and error:

eclipse.buildId=4.20.0.I20210611-1600
java.version=11.0.11
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US

org.eclipse.equinox.p2.metadata.repository
Error
Thu Aug 19 19:49:51 PDT 2021
No repository found at http://www.acanda.ch/eclipse-pmd/release/latest.

**Comment by acanda** [comment]
This issue should now be fixed. Can you try to add it from the marketplace again?

**Comment by nkavian** [comment]
Fixed.
