### ISSUE TITLE
Support older eclipse before 2021-6 ? 

### ISSUE THREAD

**Issue by go2master** [eclipse-pmd/eclipse-pmd#29]
By modify platform and rcp version ?

**Comment by acanda** [comment]
Eclipse versions released more than one year ago are not supported. 

If you need eclipse-pmd for an older version of Eclipse, you can install an older version of eclipse-pmd. If you install the plugin via the built-in Eclipse Marketplace (Help > Eclipse Marketplace...) , then it should automatically pick the latest version of eclipse-pmd that still supports your platform. Older versions of eclipse-pmd also contain older versions of PMD and will not get any updates.
