### ISSUE TITLE
Certificate error from update site

### ISSUE THREAD

**Issue by Pontesegger** [eclipse-pmd/eclipse-pmd#86]
Eclipse now uses automatic https redirects for update sites, at least in OOmph setups. Therefore

http://www.acanda.ch/eclipse-pmd/release/latest.

gets redirected to https. Unfortunately the certificate does not seem to be valid (just try to access with a recent browser)

**Comment by eclipse-pmd** [comment]
I moved the repository to https://eclipse-pmd.acanda.ch/release/latest to fix this issue. You can either manually update this URL in the "Available Software Sites" preferences or uninstall and then reinstall the plugin from the marketplace again.
